manifest:
  tag: pojntfx/dibs:latest
chart:
  srcDir: ./charts/dibs
  distDir: .bin
  cleanGlobs:
    - .bin/dibs-*.tgz
    - ./charts/dibs/charts
platforms:
  - platform: linux/amd64
    assets:
      build:
        command: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -tags netgo -ldflags '-extldflags "-static"' -o .bin/dibs-linux-amd64
        tag: pojntfx/dibs:linux-amd64
        context: .
        file: Dockerfile
      pathInImage: /usr/local/bin/dibs
      distPath: .bin/dibs-linux-amd64
      cleanGlobs:
        - .bin/dibs-linux-amd64
    tests:
      unit:
        lang:
          command: go test ./...
          tag: pojntfx/dibs-unittest:linux-amd64
          context: .
          file: Dockerfile.unitTestLang
      integration:
        lang:
          command: go run main.go --help
          tag: pojntfx/dibs-integrationtest-lang:linux-amd64
          context: .
          file: Dockerfile.integrationTestLang
        image:
          command: docker run --platform linux/amd64 -e TARGETPLATFORM=linux/amd64 pojntfx/dibs:linux-amd64 /usr/local/bin/dibs --help
          tag: pojntfx/dibs-integrationtest-image:linux-amd64
          context: .
          file: Dockerfile.integrationTestImage
        assets:
          command: .bin/dibs-linux-amd64 --help
          tag: pojntfx/dibs-integrationtest-assets:linux-amd64
          context: .
          file: Dockerfile.integrationTestAssets
        chart:
          command: helm install --name godibs .bin/dibs-*.tgz && helm delete godibs
          tag: pojntfx/dibs-integrationtest-chart:linux-amd64
          context: .
          file: Dockerfile.integrationTestChart
  - platform: linux/arm64
    assets:
      build:
        command: GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -tags netgo -ldflags '-extldflags "-static"' -o .bin/dibs-linux-arm64
        tag: pojntfx/dibs:linux-arm64
        context: .
        file: Dockerfile
      pathInImage: /usr/local/bin/dibs
      distPath: .bin/dibs-linux-arm64
      cleanGlobs:
        - .bin/dibs-linux-arm64
    tests:
      unit:
        lang:
          command: go test ./...
          tag: pojntfx/dibs-unittest:linux-arm64
          context: .
          file: Dockerfile.unitTestLang
      integration:
        lang:
          command: go run main.go --help
          tag: pojntfx/dibs-integrationtest-lang:linux-arm64
          context: .
          file: Dockerfile.integrationTestLang
        image:
          command: docker run --platform linux/arm64 -e TARGETPLATFORM=linux/arm64 pojntfx/dibs:linux-arm64 /usr/local/bin/dibs --help
          tag: pojntfx/dibs-integrationtest-image:linux-arm64
          context: .
          file: Dockerfile.integrationTestImage
        assets:
          command: .bin/dibs-linux-arm64 --help
          tag: pojntfx/dibs-integrationtest-assets:linux-arm64
          context: .
          file: Dockerfile.integrationTestAssets
        chart:
          command: helm install --name godibs .bin/dibs-*.tgz && helm delete godibs
          tag: pojntfx/dibs-integrationtest-chart:linux-arm64
          context: .
          file: Dockerfile.integrationTestChart