.dindMageJob: &dindMageJob
        image: docker:stable
        services:
                - name: docker:dind
                  command:
                          - "--experimental"
        variables:
                DOCKER_HOST: tcp://docker:2375/
        before_script:
                - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
                - apk add curl go git musl-dev
                - curl -L https://github.com/magefile/mage/releases/download/v1.9.0/mage_1.9.0_Linux-64bit.tar.gz | tar -zvxf - mage
                - chmod +x mage
                - mv mage /usr/local/bin
                - docker login ${DOCKER_REGISTRY} --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}

stages:
        - test
        - dockerBuild
        - dockerPushBinaryBuild
        - dockerManifestBuild
        - dockerManifestPush

testUnitInDockerAll:
        <<: *dindMageJob
        stage: test
        script:
                - mage testUnitInDockerAll

testIntegrationGoInDockerAll:
        <<: *dindMageJob
        stage: test
        script:
                - mage testIntegrationGoInDockerAll

testIntegrationBinaryInDockerAll:
        <<: *dindMageJob
        stage: test
        script:
                - mage testIntegrationBinaryInDockerAll

testIntegrationDockerInDockerAll:
        <<: *dindMageJob
        stage: test
        script:
                - mage testIntegrationDockerInDockerAll

buildDockerAll:
        <<: *dindMageJob
        stage: dockerBuild
        script:
                - mage buildDockerAll

pushDockerImageAll:
        <<: *dindMageJob
        stage: dockerPushBinaryBuild
        script:
                - mage pushDockerImageAll

getBinaryFromDockerImageAll:
        <<: *dindMageJob
        stage: dockerPushBinaryBuild
        script:
                - mage getBinaryFromDockerImageAll

buildDockerManifest:
        <<: *dindMageJob
        stage: dockerManifestBuild
        script:
                - mage buildDockerManifest

pushDockerManifest:
        <<: *dindMageJob
        stage: dockerManifestPush
        script:
                - mage pushDockerManifest
