unitTest:
        image: docker:stable
        services:
                - docker:dind
        variables:
                DOCKER_HOST: tcp://docker:2375/
        before_script:
                - apk add go git musl-dev
                - go get github.com/magefile/mage
        script:
                - mage unitTestInDocker
