.dindMageJob: &dindMageJob
        image: docker:stable
        services:
                - name: docker:dind
                  command:
                          - "--experimental"
        variables:
                DOCKER_HOST: tcp://docker:2375/
        before_script:
                - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
                - apk add curl go git musl-dev
                - curl -L https://github.com/magefile/mage/releases/download/v1.9.0/mage_1.9.0_Linux-64bit.tar.gz | tar -zvxf - mage
                - chmod +x mage
                - mv mage /usr/local/bin

testUnitInDockerAll:
        <<: *dindMageJob
        script:
                - mage testUnitInDocker

testIntegrationGoInDockerAll:
        <<: *dindMageJob
        script:
                - mage testIntegrationGoInDocker

testIntegrationBinaryInDockerAll:
        <<: *dindMageJob
        script:
                - mage testIntegrationBinaryInDocker
