.dindMageJob: &dindMageJob
        image: docker:stable
        services:
                - docker:dind
        variables:
                DOCKER_HOST: tcp://docker:2375/
        before_script:
                - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
                - apk add curl go git musl-dev
                - curl -L https://github.com/magefile/mage/releases/download/v1.9.0/mage_1.9.0_Linux-64bit.tar.gz | tar -zvxf - mage
                - chmod +x mage
                - mv mage /usr/local/bin

unitTestInDockerAll:
        <<: *dindMageJob
        script:
                - mage unitTestInDockerAll

integrationTestInDockerAll:
        <<: *dindMageJob
        script:
                - mage integrationTestInDockerAll

integrationTestDockerAll:
        <<: *dindMageJob
        script:
                - mage buildDockerImagesAll integrationTestDockerAll || true

# integrationTestBinariesAll:
# <<: *dindMageJob
# script:
# - mage buildDockerImagesAll getBinariesFromDockerContainersAll integrationTestBinariesAll || true
