.dindMageJob: &dindMageJob
        image: docker:stable
        services:
                - name: docker:dind
                  command:
                          - "--experimental"
        variables:
                DOCKER_HOST: tcp://docker:2375/
        before_script:
                - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
                - apk add curl go git musl-dev
                - curl -L https://github.com/magefile/mage/releases/download/v1.9.0/mage_1.9.0_Linux-64bit.tar.gz | tar -zvxf - mage
                - chmod +x mage
                - mv mage /usr/local/bin
                - docker login ${DOCKER_REGISTRY} --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}

stages:
        - test
        - dockerBuild
        - dockerPush
        - dockerManifestBuild
        - dockerManifestPush
        - binaryBuild

test:testUnitInDockerAll:
        <<: *dindMageJob
        script:
                - mage testUnitInDockerAll

test:testIntegrationGoInDockerAll:
        <<: *dindMageJob
        script:
                - mage testIntegrationGoInDockerAll

test:testIntegrationBinaryInDockerAll:
        <<: *dindMageJob
        script:
                - mage testIntegrationBinaryInDockerAll

test:testIntegrationDockerInDockerAll:
        <<: *dindMageJob
        script:
                - mage testIntegrationDockerInDockerAll

dockerBuild:buildDockerAll:
        <<: *dindMageJob
        script:
                - mage buildDockerAll

dockerPush:pushDockerImageAll:
        <<: *dindMageJob
        script:
                - mage pushDockerImageAll

dockerManifestBuild:buildDockerManifest:
        <<: *dindMageJob
        script:
                - mage buildDockerManifest

dockerManifestPush:pushDockerManifest:
        <<: *dindMageJob
        script:
                - mage pushDockerManifest

binaryBuild:getBinaryFromDockerImageAll:
        <<: *dindMageJob
        script:
                - mage getBinaryFromDockerImageAll
