.dindMageJob: &dindMageJob
        image: docker:stable
        services:
                - name: docker:dind
                  command:
                          - "--experimental"
        variables:
                DOCKER_HOST: tcp://docker:2375/
        before_script:
                - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
                - apk add curl go git musl-dev
                - curl -L https://github.com/magefile/mage/releases/download/v1.9.0/mage_1.9.0_Linux-64bit.tar.gz | tar -zvxf - mage
                - chmod +x mage
                - mv mage /usr/local/bin
                - docker login ${DOCKER_REGISTRY} --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}

testUnitInDockerAll:
        <<: *dindMageJob
        script:
                - mage testUnitInDockerAll

testIntegrationGoInDockerAll:
        <<: *dindMageJob
        script:
                - mage testIntegrationGoInDockerAll

testIntegrationBinaryInDockerAll:
        <<: *dindMageJob
        script:
                - mage testIntegrationBinaryInDockerAll

testIntegrationDockerInDockerAll:
        <<: *dindMageJob
        script:
                - mage testIntegrationDockerInDockerAll

buildAndPushDockerImageAll:
        <<: *dindMageJob
        script:
                - mage buildDockerAll pushDockerImageAll
        dependencies:
                - testUnitInDockerAll
                - testIntegrationGoInDockerAll
                - testIntegrationDockerInDockerAll
                - testIntegrationBinaryInDockerAll

buildAndPushDockerManifest:
        <<: *dindMageJob
        script:
                - mage buildDockerManifest pushDockerManifest
        dependencies:
                - buildAndPushDockerImageAll

getBinaryFromDockerImageAll:
        <<: *dindMageJob
        script:
                - mage getBinaryFromDockerImageAll
        dependencies:
                - buildAndPushDockerImageAll
