FROM arm32v7/golang:1.13.5-buster AS build
WORKDIR /app

ENV ARCHITECTURE=arm

RUN go get github.com/magefile/mage
COPY ./go.mod ./go.sum ./
RUN go mod download

COPY ./magefile.go ./magefile.go
COPY ./main.go ./main.go
COPY ./cmd ./cmd
COPY ./pkg ./pkg

RUN mage buildBinary

FROM arm32v7/debian:buster-slim
COPY --from=build /app/.bin/godibs-arm /usr/local/bin/godibs
EXPOSE 25000
CMD ["/usr/local/bin/godibs", "server"]
