# syntax=docker/dockerfile:experimental
FROM --platform=$TARGETPLATFORM golang
ARG TARGET
ARG TARGETPLATFORM

WORKDIR /app

RUN curl -Lo /tmp/dibs https://nx904.your-storageshare.de/s/ZWxkmmQW37fHt9J/download
RUN install /tmp/dibs /usr/local/bin

ADD . .

CMD dibs -unitTests