# syntax=docker/dockerfile:experimental
FROM --platform=$TARGETPLATFORM golang:1.13.5-buster AS build
WORKDIR /app
ARG TARGETPLATFORM

COPY ./go.mod ./go.sum ./
RUN go mod download

COPY ./main.go ./main.go
COPY ./cmd ./cmd
COPY ./pkg ./pkg

RUN go run main.go --platform $TARGETPLATFORM binary build

FROM --platform=$TARGETPLATFORM debian:buster-slim
WORKDIR /app
ARG TARGETPLATFORM

RUN apt update -y
RUN apt install -y go git

COPY ./go.mod ./go.sum ./
RUN go mod download

COPY ./main.go ./main.go
COPY ./cmd ./cmd
COPY ./pkg ./pkg

COPY --from=build /app/.bin ./.bin

CMD go run main.go --platform $TARGETPLATFORM binary integrationtest
