# syntax=docker/dockerfile:experimental
FROM --platform=$TARGETPLATFORM docker:stable
WORKDIR /app
ARG TARGETPLATFORM

RUN apk update
RUN apk add go git

COPY ./go.mod ./go.sum ./
RUN go mod download

COPY ./.dibs.yml ./.dibs.yml
COPY ./main.go ./main.go
COPY ./cmd ./cmd
COPY ./pkg ./pkg

CMD go run main.go pipeline integrationtest image --platform $TARGETPLATFORM
