# syntax=docker/dockerfile:experimental
FROM --platform=$TARGETPLATFORM golang:1.13.5-buster
WORKDIR /app
ARG TARGETPLATFORM

COPY ./go.mod ./go.sum ./
RUN go mod download

COPY ./main.go ./main.go
COPY ./cmd ./cmd
COPY ./pkg ./pkg

CMD go run main.go --platform $TARGETPLATFORM lang unittest
