FROM golang:alpine

WORKDIR /app

RUN apk add -u curl

RUN curl -Lo /tmp/dibs https://nx904.your-storageshare.de/s/FkBmkPRPPC7Ea2A/download
RUN install /tmp/dibs /usr/local/bin

ADD . .

CMD dibs -dev
