apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app{{ if .Values.dev}}-dev{{ end }}
spec:
  selector:
    matchLabels:
      app: test-app{{ if .Values.dev}}-dev{{ end }}
  template:
    metadata:
      labels:
        app: test-app{{ if .Values.dev}}-dev{{ end }}
    spec:
      containers:
        - name: test-app{{ if .Values.dev}}-dev{{ end }}
          image: {{ .Values.image }}
          {{ if .Values.dev }}
          envFrom:
            - configMapRef:
                name: test-app{{ if .Values.dev }}-dev{{ end }}
          {{ end }}
  {{ if .Values.dev }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-app{{ if .Values.dev }}-dev{{ end }}
data:
  TARGETPLATFORM: {{ .Values.platform }}
  {{ end }}

