package config

var (
	PIPELINE_UP_DIR_SRC       string
	PIPELINE_UP_DIR_PUSH      string
	PIPELINE_UP_DIR_WATCH     string
	PIPELINE_UP_FILE_MOD      string
	PIPELINE_UP_BUILD_COMMAND string
	PIPELINE_UP_TEST_COMMAND  string
	PIPELINE_UP_START_COMMAND string
	PIPELINE_UP_REGEX_IGNORE  string

	PIPELINE_DOWN_MODULES     string
	PIPELINE_DOWN_DIR_MODULES string
)
