package config

import "os"

var (
	PIPELINE_UP_DIR_SRC       = os.Getenv("PIPELINE_UP_DIR_SRC")
	PIPELINE_UP_DIR_PUSH      = os.Getenv("PIPELINE_UP_DIR_PUSH")
	PIPELINE_UP_DIR_WATCH     = os.Getenv("PIPELINE_UP_DIR_WATCH")
	PIPELINE_UP_FILE_MOD      = os.Getenv("PIPELINE_UP_FILE_MOD")
	PIPELINE_UP_BUILD_COMMAND = os.Getenv("PIPELINE_UP_BUILD_COMMAND")
	PIPELINE_UP_TEST_COMMAND  = os.Getenv("PIPELINE_UP_TEST_COMMAND")
	PIPELINE_UP_START_COMMAND = os.Getenv("PIPELINE_UP_START_COMMAND")

	PIPELINE_DOWN_MODULES = os.Getenv("PIPELINE_DOWN_MODULES")
)
