# syntax=docker/dockerfile:experimental
FROM --platform=$TARGETPLATFORM golang:alpine
ARG DIBS_TARGET
ARG TARGETPLATFORM

WORKDIR /app

RUN apk add -u curl git

RUN curl -Lo /tmp/dibs https://nx904.your-storageshare.de/s/ZWxkmmQW37fHt9J/download
RUN install /tmp/dibs /usr/local/bin

ENV GO111MODULE=on

RUN go get github.com/go-delve/delve/cmd/dlv

ADD . .

CMD dibs -dev
